#!/usr/bin/env python3

from pathlib import Path


def main() -> None:
    # __file__ is docs/scripts/sync_readme_to_index.py; repo root is two levels up
    root = Path(__file__).resolve().parents[2]
    readme_path = root / "README.md"
    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    index_path = docs_dir / "index.md"

    if not readme_path.is_file():
        raise SystemExit("README.md not found at repository root")

    content = readme_path.read_text(encoding="utf-8")
    header = "<!-- Auto-generated from README.md. Do not edit this file directly. -->\n\n"
    index_path.write_text(header + content, encoding="utf-8")


if __name__ == "__main__":
    main()
